Add support for darwin/clang
oodler577/p5-Alien-OpenMP pull request #11
Opened 2021-10-06 11:48 UTC by kiwiroy

This pull request adds support for clang on macOS. This involves a switch to a more `Alien::Build` style, including an `alienfile`, compiling at `probe` time with `Probe::CBuilder`, and only supporting system installs. AB manages the runtime settings, making `Alien::OpenMP` more simple. The other side of this is that there's a new module to store the possible scenarios and a dependency on `Alien::Build`.

Thanks for considering this request.

2021-10-06 13:47 UTC, mohawk2 requested changes
This looks really good overall! I've enabled the CI.

2021-10-06 13:47 UTC, mohawk2 commented on lib/Alien/OpenMP.pm
> +our $VERSION = '0.003003';
Could you undo this version change? That's for release person to do :-)

2021-10-07 12:34 UTC, kiwiroy commented on lib/Alien/OpenMP.pm
> +our $VERSION = '0.003003';
done

2021-10-10 20:21 UTC, mohawk2 approved these changes

2021-10-10 20:21 UTC, merged

2021-10-10 20:49 UTC, mohawk2 commented
Thanks for this! Released as 0.003003.

2021-10-14 13:38 UTC, oodler577 commented
thank you, @kiwiroy and @mohawk2